% Configure Matlab Path to Include the full crlEEG
function addCRLEEGPath()
[currDir,~,~] = fileparts(mfilename('fullpath'));

addpath(currDir);
addpath(...
     fullfile(currDir, 'external', 'BioSig_2.92', 'tsa'), ...
     fullfile(currDir, 'external', 'BioSig_2.92', 'biosig', 'viewer', 'help'), ...
     fullfile(currDir, 'external', 'BioSig_2.92', 'biosig', 'viewer', 'utils'), ...
     fullfile(currDir, 'external', 'BioSig_2.92', 'biosig', 'viewer'), ...
     fullfile(currDir, 'external', 'BioSig_2.92', 'biosig', 't501_VisualizeCoupling'), ...
     fullfile(currDir, 'external', 'BioSig_2.92', 'biosig', 't500_Visualization'), ...
     fullfile(currDir, 'external', 'BioSig_2.92', 'biosig', 't490_EvaluationCriteria'), ...
     fullfile(currDir, 'external', 'BioSig_2.92', 'biosig', 't450_MultipleTestStatistic'), ...
     fullfile(currDir, 'external', 'BioSig_2.92', 'biosig', 't400_Classification'), ...
     fullfile(currDir, 'external', 'BioSig_2.92', 'biosig', 't300_FeatureExtraction'), ...
     fullfile(currDir, 'external', 'BioSig_2.92', 'biosig', 't250_ArtifactPreProcessingQualityControl'), ...
     fullfile(currDir, 'external', 'BioSig_2.92', 'biosig', 't200_FileAccess'), ...
     fullfile(currDir, 'external', 'BioSig_2.92', 'biosig', 'doc'), ...
     fullfile(currDir, 'external', 'BioSig_2.92', 'biosig', 'demo'), ...
     fullfile(currDir, 'external', 'BioSig_2.92', 'biosig'));


