%%
clear all;
cd /common/epilepsysurgicalplanning/processed/Case195/scan04_20141123/sourceanalysis/models/skinCRL_skullNONE_segNVM_wmCRL/clinical;

load ElectrodeNodes

elec = crlEEG.type.sensor.electrode(...
            'label', Electrodes.Labels,...
            'position',Electrodes.Positions,...
            'nodes',num2cell(Electrodes.Nodes),...
            'voxels',Electrodes.Voxels,...
            'impedance',Electrodes.Impedance);
    
fid = crlEEG.type.sensor.electrode('label',Electrodes.FIDLabels,'position',Electrodes.FIDPositions);
