%%
clear all;
cd /common/epilepsysurgicalplanning/processed/Case195/scan04_20141123/sourceanalysis/models/skinCRL_skullNONE_segNVM_wmCRL/clinical;

load ElectrodeNodes

test = crlEEG.head.model.EEG.electrode(...
            'label', Electrodes.Labels,...
            'position',Electrodes.Positions,...
            'nodes',num2cell(Electrodes.Nodes),...
            'voxels',Electrodes.Voxels,...
            'impedance',Electrodes.Impedance);
          
